version: "3.7"

services:
  flexml:
    image: uogsoe/docker-demo:0.2
    ports:
      - "3000:3000"
    deploy:
      replicas: 5
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        failure_action: rollback
        order: start-first

  redis:
    image: redis:5.0.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
